name: Publish Codemirror LS

on:
  workflow_run:
    workflows: ["Codemirror LS Test"]
    types:
      - completed
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install mise
      uses: jdx/mise-action@v2
        
    - name: Install dependencies
      working-directory: ./codemirror-ls
      run: npm install
        
    - name: Run tests
      working-directory: ./codemirror-ls
      run: npm run build

    - name: Publish package
      working-directory: ./codemirror-ls
      run: npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
