on:
  push:
    branches:
      - main

jobs:
  deploy:
    defaults:
      run:
        working-directory: demo

    runs-on: ubuntu-latest
    # Cloudflare has [worker builds](https://developers.cloudflare.com/workers/wrangler/) but 
    # we also need to deploy a container to Cloudflare Containers and a durable object.
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: npm ci
      - name: Install wrangler
        run: npm install -g wrangler@4.29.1
      - name: Wrangler deploy
        run: npx wrangler@4.29.1 deploy
        env:
          NODE_ENV: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
