name: Test ws-ls-server

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install mise
      uses: jdx/mise-action@v2
        
    - name: Run tests
      working-directory: ./ls-ws-server
      run: deno task test:ci
